### ISSUE TITLE
Issue with upgrade

### ISSUE THREAD

**Issue by g0pinath** [Azure/phippyandfriends#47]
This works perfectly, and I would like to mention one issue where the upgrade fails when there is no existing release. I had to use helm install the first time and then change it to upgrade for subsequent releases. I could add a condition to check if there is an existing release before doing an upgrade.

**Comment by mathieu-benoit** [comment]
Hi @g0pinath, which command/part are you referring? Are you using `helm upgrade --install`?

**Comment by g0pinath** [comment]
helm upgrade --install that is in the repo gives an error
Error: UPGRADE FAILED: "myapp" has no deployed releases
https://github.com/helm/helm/issues/7160
If I changed it to helm install it will work, and then I need to change it back to helm upgrade --install for subsequent releases.

**Comment by mathieu-benoit** [comment]
Which version of helm are you using? Are you in this scenario https://github.com/helm/helm/issues/5595#issuecomment-603685773 where you got failed deployment/release before the first successful `helm upgrade --install`?

**Comment by mathieu-benoit** [comment]
Hi @g0pinath, closing this issue since it seems directly helm related. Happy to assist more if you still have the issue and are able to provide more information/context like asked above. Thanks.
